apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: azizul2go/two-tier-backend-image
        name: two-tier-backend-image
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "1"
        envFrom:
          - configMapRef:
              name: mysql-config
        resources: {}
status: {}
